<x-master-layout>

    @push('css')
        <link rel="stylesheet" href="{{ asset('assets/auth/backend/css/project.css') }}">
    @endpush

    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

        <script>
            // Konfigurasi Global (Dinamis dari PHP)
            window.dataTableId = @json($dataTableId);
            window.urlData = @json($dataUrl);
            window.urlEdit = @json($editUrl);
            window.urlShow = @json($showUrl);
            window.urlDestroy = @json($destroyUrl);
            // window.canRead = @json(auth()->user()->can('read ' . $permissionAkses));
            // window.canUpdate = @json(auth()->user()->can('update ' . $permissionAkses));
            // window.canDelete = @json(auth()->user()->can('delete ' . $permissionAkses));
        </script>

        <script src="{{ asset('assets/auth/backend/js/custom-table.js') }}"></script>
        <script src="{{ asset('assets/auth/backend/js/project.js') }}"></script>
    @endpush

    <!-- Page Header -->
    <div class="page-header" data-aos="fade-down" data-aos-duration="500">
        <div class="ph-left">
            <div class="ph-icon"><i class="{{ $icon }}"></i></div>
            <div>
                <div class="ph-title">{{ $title }}</div>
                <div class="ph-sub">{{ $subtitle }}</div>
            </div>
        </div>
        <div class="breadcrumb-bar">
            <a href="{{ route('dashboard') }}"><i class="bi bi-house-fill"></i> Home</a>
            <span class="sep"><i class="bi bi-chevron-right"></i></span>
            <span class="here">{{ $title }}</span>
        </div>
    </div>

    <!-- Mini stat cards -->
    @include('pages.project.partials.stats-view')

    <!-- Table card -->
    <div class="crd mb-24" data-aos="fade-up" data-aos-delay="100">

        @include('pages.project.partials.filter-view')

        <div class="table-responsive">
            <table class="table-pms" id="tblProject">
                <thead>
                    <tr>
                        <th style="width:46px">#</th>
                        <th class="th-sort" data-col="name">Nama Project <i class="bi bi-chevron-expand sort-ico"></i></th>
                        <th style="width:130px">Status</th>
                        <th style="width:130px">Progress</th>
                        <th style="width:100px">PIC</th>
                        <th class="th-sort" data-col="start_date" style="width:105px">Mulai <i
                                class="bi bi-chevron-expand sort-ico"></i></th>
                        <th class="th-sort" data-col="deadline" style="width:140px">Deadline <i
                                class="bi bi-chevron-expand sort-ico"></i></th>
                        <th class="th-sort" data-col="created_by" style="width:120px">Pembuat <i
                                class="bi bi-chevron-expand sort-ico"></i></th>
                        <th class="th-center" style="width:120px">Aksi</th>
                    </tr>
                </thead>
                <tbody id="dataBody">
                    <!-- Data loaded via AJAX -->
                </tbody>
            </table>
        </div>

        <!-- Empty State -->
        <div id="emptyState" class="tbl-empty d-none">
            <i class="bi bi-folder-x"></i>
            <div class="et">Belum Ada Project</div>
            <div class="es">Mulai dengan menambahkan project baru untuk tim Anda.</div>
        </div>

        <!-- Pagination -->
        <div class="pagi">
            <div class="pagi-info" id="pagiInfo">
                Menampilkan <span>0</span> – <span>0</span> dari <span>0</span> project
            </div>
            <div class="pagi-btns" id="pagiBtns">
                <!-- Buttons generated by JS -->
            </div>
        </div>
    </div>

</x-master-layout>
