<x-master-layout>

    @push('css')
        <link rel="stylesheet" href="{{ asset('assets/auth/backend/css/project.css') }}">
    @endpush

    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

        <script>
            // Konfigurasi Global (Dinamis dari PHP)
            window.dataTableId = @json($dataTableId);
            window.urlData = @json($dataUrl);
            window.urlEdit = @json($editUrl);
            window.urlShow = @json($showUrl);
            window.urlDestroy = @json($destroyUrl);
            window.canRead = @json(auth()->user()->can('read ' . $permissionAkses));
            window.canUpdate = @json(auth()->user()->can('update ' . $permissionAkses));
            window.canDelete = @json(auth()->user()->can('delete ' . $permissionAkses));
        </script>

        <script src="{{ asset('assets/auth/backend/js/custom-table.js') }}"></script>
        <script src="{{ asset('assets/auth/backend/js/project.js') }}"></script>
    @endpush

    <!-- Page Header -->
    <div class="pg-hd" data-aos="fade-down" data-aos-duration="500">
        <div class="pg-hd-left">
            <div class="pg-ico"><i class="{{ $icon }}"></i></div>
            <div>
                <div class="pg-title">{{ $title }}</div>
                <div class="pg-sub">{{ $subtitle }}</div>
            </div>
        </div>
        <div class="pg-actions">
            <div class="bc d-none d-md-flex">
                <a href="{{ route('dashboard') }}"><i class="bi bi-house-fill"></i>&nbsp;Home</a>
                <span class="sep"><i class="bi bi-chevron-right"></i></span>
                <span class="here">{{ $title }}</span>
            </div>
        </div>
    </div>

    <!-- Mini stat cards -->
    @include('pages.project.partials.stats-view')

    @include('pages.project.partials.filter-view')

    <!-- Table card -->
    <div class="tbl-card" data-aos="fade-up" data-aos-delay="80">

        <div class="table-responsive">
            <table class="dtbl" id="tblProject">
                <thead class="text-center">
                    <tr>
                        <th style="text-align:center;width:42px">#</th>
                        <th class="th-sort" data-col="name" style="min-width:250px">Nama Project <i class="bi bi-chevron-expand sort-ico"></i></th>
                        <th style="min-width:130px">Status</th>
                        <th style="min-width:130px">Progress</th>
                        <th style="min-width:140px">Tim Pelaksana</th>
                        <th class="th-sort" data-col="start_date" style="min-width:105px">Mulai <i
                                class="bi bi-chevron-expand sort-ico"></i></th>
                        <th class="th-sort" data-col="deadline" style="min-width:140px">Deadline <i
                                class="bi bi-chevron-expand sort-ico"></i></th>
                        <th class="th-sort" data-col="created_by" style="min-width:120px">Pembuat <i
                                class="bi bi-chevron-expand sort-ico"></i></th>
                        <th style="text-align:center;width:100px">Aksi</th>
                    </tr>
                </thead>
                <tbody id="dataBody">
                    <!-- Data loaded via AJAX -->
                </tbody>
            </table>
        </div>

        <!-- Empty State -->
        <div id="emptyState" class="tbl-empty d-none">
            <i class="bi bi-folder-x"></i>
            <div class="et">Belum Ada Project</div>
            <div class="es">Mulai dengan menambahkan project baru untuk tim Anda.</div>
        </div>

        <!-- Pagination -->
        <div class="tbl-foot">
            <div class="tbl-info" id="pagiInfo">
                Menampilkan <span>0</span> – <span>0</span> dari <span>0</span> project
            </div>
            <div class="pag" id="pagiBtns">
                <!-- Buttons generated by JS -->
            </div>
        </div>
    </div>


</x-master-layout>
