<x-master-layout>
    @section('title', $title)

    @push('css')
        <link rel="stylesheet" href="{{ asset('assets/auth/backend/css/project.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/auth/backend/css/role-management.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/auth/backend/css/kategori-dokumen.css') }}">
    @endpush

    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
        <script>
            window.urlBase = "{{ url('kategori-dokumen') }}";
            window.urlData = "{{ route('kategori-dokumen.getData') }}";
            window.urlStore = "{{ route('kategori-dokumen.store') }}";
        </script>
        <script src="{{ asset('assets/auth/backend/js/custom-table.js') }}"></script>
        <script src="{{ asset('assets/auth/backend/js/kategori-dokumen.js') }}?v={{ time() }}"></script>
    @endpush

    <!-- Page Header -->
    <div class="pg-hd" data-aos="fade-down" data-aos-duration="500">
        <div class="pg-hd-left">
            <div class="pg-ico"><i class="bi bi-tags-fill"></i></div>
            <div>
                <div class="pg-title">{{ $title }}</div>
                <div class="pg-sub">{{ $subtitle }}</div>
            </div>
        </div>
        <div class="pg-actions">
            <div class="bc d-none d-md-flex">
                <a href="{{ route('dashboard') }}"><i class="bi bi-house-fill"></i>&nbsp;Home</a>
                <span class="sep"><i class="bi bi-chevron-right"></i></span>
                <span class="here">{{ $title }}</span>
            </div>
        </div>
    </div>

    <!-- Stats -->
    <div class="row g-3 mb-4" data-aos="fade-up" data-aos-delay="50">
        <div class="col-md-6">
            <div class="sc c w-100 m-0">
                <div class="sc-ico c"><i class="bi bi-tag-fill"></i></div>
                <div>
                    <div class="sc-val" id="statTotal">{{ $stats['total'] }}</div>
                    <div class="sc-lbl">Total Kategori</div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="sc g w-100 m-0">
                <div class="sc-ico g"><i class="bi bi-file-earmark-check-fill"></i></div>
                <div>
                    <div class="sc-val" id="statUsed">{{ $stats['used'] }}</div>
                    <div class="sc-lbl">Jenis Kategori Terpakai</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Toolbar -->
    <div class="tbar" data-aos="fade-up" data-aos-delay="60">
        <div class="tbar-search">
            <i class="bi bi-search"></i>
            <input type="text" id="searchInput" placeholder="Cari nama kategori atau deskripsi..." />
        </div>

        <div class="filter-wrap" style="display: flex; gap: 8px; align-items: center;">
            <button class="btn-reset" id="btnReset" title="Reset Filter">
                <i class="bi bi-arrow-counterclockwise"></i>
            </button>
        </div>

        <div class="tbar-right">
            <button class="btn-add" id="btnAdd">
                <span><i class="bi bi-plus-lg"></i> Tambah Kategori</span>
            </button>
        </div>
    </div>

    <!-- Table card -->
    <div class="tbl-card" data-aos="fade-up" data-aos-delay="80">
        <div class="table-responsive">
            <table class="dtbl" id="tblKategori">
                <thead>
                    <tr>
                        <th style="text-align:center;width:42px">#</th>
                        <th style="min-width:200px">Nama Kategori</th>
                        <th style="min-width:150px">Slug</th>
                        <th style="min-width:250px">Deskripsi</th>
                        <th style="min-width:150px">Dibuat Oleh</th>
                        <th style="min-width:120px">Tanggal</th>
                        <th style="text-align:center;width:100px">Aksi</th>
                    </tr>
                </thead>
                <tbody id="dataBody">
                    <!-- Data loaded via AJAX -->
                </tbody>
            </table>
        </div>

        <!-- Empty State -->
        <div id="emptyState" class="tbl-empty d-none">
            <i class="bi bi-tag-fill"></i>
            <div class="et">Belum Ada Kategori</div>
            <div class="es">Buat kategori baru untuk mengelompokkan dokumen proyek Anda.</div>
        </div>

        <!-- Pagination -->
        <div class="tbl-foot">
            <div class="tbl-info" id="pagiInfo">
                Menampilkan <span>0</span> – <span>0</span> dari <span>0</span> kategori
            </div>
            <div class="pag" id="pagiBtns">
                <!-- Buttons generated by JS -->
            </div>
        </div>
    </div>    @push('modals')
        @include('pages.kategori-dokumen.partials.modal-form')
    @endpush
</x-master-layout>
>
